syntax = "proto3";

package url_shortener;

option go_package = "github.com/aube/url-shortener/internal/api/grpc/proto";

service UrlShortener {
    rpc SaveURL (SaveURLRequest) returns (SaveURLResponse) {}
    rpc GetURL (GetURLRequest) returns (GetURLResponse) {}
}

message SaveURLRequest {
    string original_url = 1;
    string base_url = 2;
}

message SaveURLResponse {
    string short_url = 1;
}

message GetURLRequest {
    string id = 1;
}

message GetURLResponse {
    string original_url = 1;
}

// Error messages
message Error {
    string message = 1;
    int32 code = 2;
}
